## 1、提示

![image-20220812154811891](C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220812154811891.png)

需要有一个axios.min.map文件，将压缩后的代码映射为原本的有逻辑的代码，从而浏览器能更方便的提示错误。

因为axios是非常官方的库，没有这个也无所谓，一般不会出错。

可以按照下图步骤关闭这个警告提示

<img src="C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220812155609010.png" alt="image-20220812155609010" style="zoom: 67%;" />

## 2、CancelToken和isCancel

Token用来标识唯一的东西。

为什么不能自己指定token，而是一定要用axios提供的CancelToken呢？

- 因为axios担心你自己指定可能会出现重复的，所以给了个API让你来指定

### 2.1 基本使用

- 发送请求时，配置`cancelToken`属性，值是`new CancelToken(executor)`，`executor`是一个函数，==函数的参数由axios提供，由axios调用，参数是取消该次请求的函数==。==将该取消函数给一个全局变量==，就能够在点击取消按钮时，通过全局变量调用该函数，从而可以取消请求

- ==取消发送请求后，axios返回的Promise实例状态会变为失败，因此定义的失败回调函数会执行==。但是这个error并不是服务器返回的错误，而是axios给的一个错误。
- ==如果在调用cancel('xxx')的时候，传递了一些参数，那么这些参数，就会被axios传递给失败状态的回调函数，作为失败回调函数的error参数中的属性`error.message`。==

``` js
const CancelToken = axios.CancelToken;
let cancel;

axios.get('/user/21345', {
    cancelToken: new CancelToken(function executor(c){ //c是一个函数，调用c就可以关闭本次请求
        cancel = c;
    })
}).then(
	response => {console.log('成功了', response.data)},
    error => {console.log('失败了', error)}
)
cancel('xxxx')

```

- 可以发现，无==论是发送请求到达服务器出现错误，还是用户自己点击取消请求，都会导致axios返回的Promise实例状态会变为失败，从而导致失败状态的回调函数被调用，也就是错误后的提示信息是一样的==。
- 为了加以区分，我们可以==利用两者error的不同==，发送请求到达服务器出现错误的error和用户自己点击取消请求的error是不同的。==axios提供了一个API`isCancel()`来判断是否是取消请求时出现的错误==

``` js
const {CancelToken, isCancel} = axios;
let cancel;

axios.get('/user/21345', {
    cancelToken: new CancelToken(function executor(c){ //c是一个函数，调用c就可以关闭本次请求
        cancel = c;
    })
}).then(
	response => {console.log('成功了', response.data)},
    error => {
        if(isCancel(error)){
            //进入这里，说明是用户自己取消的请求
            console.log('取消请求成功，取消的原因是', error.message)
        }else{
            //进入这里，说明是请求有问题
            console.log('失败了', error)
        }
    }
)
cancel('xxxx')

```

### 2.2 示例

点击按钮1发送一个延迟请求，点击按钮2取消该请求

``` html
  <body>
    <button id="btn_delay">点我发送延时请求</button><br />
    <button id="btn_cancel">点我取消请求</button>

    <script>
      const btnDelay = document.getElementById("btn_delay");
      const btnCancel = document.getElementById("btn_cancel");
      const { CancelToken, isCancel } = axios;
      let cancel; //要用let，因为cancel可能会被多次赋值

      btnDelay.onclick = () => {
        axios({
          url: "http://localhost:5000/test1",
          params: {
            delay: 3000,
          },
          cancelToken: new CancelToken(function executor(c) {
            //c是一个函数，调用c就可以关闭本次请求
            cancel = c;
          }),
        }).then(
          (response) => {
            console.log("请求发送成功，拿到的数据是", response.data);
          },
          (error) => {
            if (isCancel(error)) {
              console.log("成功取消请求", error.message);
            } else {
              console.log("请求发送失败，错误是", error);
            }
          }
        );
      };

      btnCancel.onclick = () => {
        console.log(1);
        cancel("成功取消请求");
      };
    </script>
  </body>
```

点击按钮1就取消之前发送的请求，并重新发送请求。

``` html
  <body>
    <button id="btn_delay">点我发送延时请求</button><br />
    <button id="btn_cancel">点我取消请求</button>

    <script>
      const btnDelay = document.getElementById("btn_delay");
      const btnCancel = document.getElementById("btn_cancel");
      const { CancelToken, isCancel } = axios;
      let cancel; //要用let，因为cancel可能会被多次赋值

      btnDelay.onclick = () => {
        // cancel没有给初始值，所以其初始值是undefined，隐式转换中undefined会被转换为false。所以只要用一个if语句判断 cancel 不是 undefined，那么就取消该请求。
        if (cancel) cancel("取消请求");
        axios({
          url: "http://localhost:5000/test1",
          params: {
            delay: 3000,
          },
          cancelToken: new CancelToken(function executor(c) {
            //c是一个函数，调用c就可以关闭本次请求
            cancel = c;
          }),
        }).then(
          (response) => {
            console.log("请求发送成功，拿到的数据是", response.data);
          },
          (error) => {
            if (isCancel(error)) {
              console.log("成功取消请求", error.message);
            } else {
              console.log("请求发送失败，错误是", error);
            }
          }
        );
      };
    </script>
  </body>
```

## 3、==拦截器和取消请求配合使用==

点击按钮1，会取消目前正在发送的请求，然后发送新的请求1

点击按钮2，会取消目前正在发送的请求，然后发送新的请求2

点击按钮3，会取消目前正在发送的请求，然后发送新的请求3

- 通过观察，当我们各自在点击按钮后的操作是相似的，当我们写出代码时，会发现以下三部分都是重复的。
  - <img src="C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220812174221195.png" alt="image-20220812174221195" style="zoom:50%;" />
- 所以我们想把这部分代码提取出来，想到使用==请求拦截器，为它们取消之前发送的请求，添加token==。同时在==响应拦截器里，为所有成功的请求直接返回服务器的响应数据，为错误的请求拦截错误，统一处理==
- 那么我们就==不必为每个请求设置失败的回调函数，因为已经被拦截了==
- 所以我们用`async await`等待成功的结果即可。

```  html
  <body>
    <button id="btn_delay1">点我发送延时请求1</button><br />
    <button id="btn_delay2">点我发送延时请求2</button><br />
    <button id="btn_delay3">点我发送延时请求3</button><br />
    <button id="btn_cancel">点我取消请求</button>

    <script>
      const btnDelay1 = document.getElementById("btn_delay1");
      const btnDelay2 = document.getElementById("btn_delay2");
      const btnDelay3 = document.getElementById("btn_delay3");
      const btnCancel = document.getElementById("btn_cancel");
      const { CancelToken, isCancel } = axios;
      let cancel; //要用let，因为cancel可能会被多次赋值

      // 在每个请求发送前，都给它们一个独一无二的token
      axios.interceptors.request.use((config) => {
        // 取消之前发送的请求
        if (cancel) cancel("取消请求");
        config.cancelToken = new CancelToken((c) => {
          cancel = c;
        });
        return config;
      });

      //   统一为请求拦截错误
      axios.interceptors.response.use(
        (response) => {
          return response.data;
        },
        (error) => {
          if (isCancel(error)) {
            console.log("取消请求成功", error.message);
          } else {
            console.log("请求出现错误", error);
          }
          // 这一步使得发送请求的那个axios返回的Promise实例对象状态为pending，也就终止了调用。
          return new Promise(() => {});
        }
      );

      axios.defaults.baseURL = "http://localhost:5000";
      btnDelay1.onclick = async () => {
        // cancel没有给初始值，所以其初始值是undefined，隐式转换中undefined会被转换为false。所以只要用一个if语句判断 cancel 不是 undefined，那么就取消该请求。
        const result = await axios({
          url: "/test1",
          params: {
            delay: 3000,
          },
        });
        console.log("发送请求1成功", result);
      };

      btnDelay2.onclick = async () => {
        // cancel没有给初始值，所以其初始值是undefined，隐式转换中undefined会被转换为false。所以只要用一个if语句判断 cancel 不是 undefined，那么就取消该请求。
        const result = await axios({
          url: "/test2",
          params: {
            delay: 3000,
          },
        });
        console.log("请求发送成功", result);
      };

      btnCancel.onclick = () => {
        console.log(1);
        cancel("成功取消请求");
      };
    </script>
  </body>
```

